import { useState } from 'react';
import { Link, useSearchParams, useNavigate } from 'react-router-dom';
import { resetPasswordRequest } from '../api/authApi';

const ResetPassword = () => {
  const [params] = useSearchParams(); const navigate = useNavigate(); const token = params.get('token') || ''; const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (e) => { e.preventDefault(); setError(''); if (!token) return setError('Reset link is missing or invalid.'); if (password.length < 6) return setError('Password must be at least 6 characters.'); if (password !== confirm) return setError('Passwords do not match.'); setLoading(true); try { const r = await resetPasswordRequest({ token, password }); setMessage(r.message); setTimeout(() => navigate('/login', { replace: true, state: { message: r.message } }), 900); } catch (err) { setError(err.response?.data?.message || 'Could not reset password.'); } finally { setLoading(false); } };
  return <div className="flex min-h-screen items-center justify-center bg-slate-50 px-4"><div className="w-full max-w-sm rounded-xl bg-white p-8 shadow-sm"><h1 className="mb-2 text-2xl font-semibold text-slate-900">Reset password</h1>{message && <div className="mb-4 rounded-md bg-green-50 px-3 py-2 text-sm text-green-700">{message}</div>}{error && <div className="mb-4 rounded-md bg-red-50 px-3 py-2 text-sm text-red-600">{error}</div>}<form onSubmit={submit} className="space-y-4"><input type="password" minLength={6} required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="New password" className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm" /><input type="password" minLength={6} required value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Confirm password" className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm" /><button disabled={loading} className="w-full rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-60">{loading ? 'Resetting...' : 'Reset password'}</button></form><p className="mt-4 text-center text-sm"><Link to="/login" className="font-medium text-indigo-600 hover:underline">Back to sign in</Link></p></div></div>;
};
export default ResetPassword;
